### ISSUE TITLE
Typo on $let function is explanation

### ISSUE THREAD

**Issue by Neodevils** [AkaruiDevelopment/aoi.js-documentation#4]
Hello 👋🏻

I was checking out the functions and I noticed there's a wrong information about `$let` & `$get` functions.

Instead of typing "gender" on `$get` function, it's written as "Ayaka" which would occur an error. 

https://github.com/AkaruiDevelopment/aoi.js-documentation/blob/8431ae807fd965e2f36000f07283f2ef72ccdc4d/src/functions/util/let.md?plain=1#L32

**Comment by Faf4a** [comment]
oops mb

**Comment by Neodevils** [comment]
> oops mb

It's okay 😉

**Comment by Leref** [comment]
Resolved
